# Generated by Django 3.1.2 on 2020-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomers',
            name='CurrentBalance',
            field=models.IntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycustomers',
            name='accountnumber',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mycustomers',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
