# Generated by Django 3.1.2 on 2020-10-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201015_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomers',
            name='emailid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycustomers',
            name='CurrentBalance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mycustomers',
            name='accountnumber',
            field=models.IntegerField(),
        ),
    ]
